import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Provider } from "@/component/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EventBricks",
  description: "Generated by Typebricks app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
