import { Inter } from "next/font/google";
import "@/styles/globals.css";

import { Provider } from "@/components/providers";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Eventbricks",
  description: "Generated by Typebricks Team",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Provider>{children}</Provider>
            </body>
        </html>
    );
}