### List Events

GET https://eventmakers-api.vercel.app/api/events


### List Single Events

GET https://eventmakers-api.vercel.app/api/events/:id


### Create Events

POST https://eventmakers-api.vercel.app/api/events

{
    "name": "",
    "description": "",
    "location": "",
    "date": "",
    "authorId": ""
}


### Join Events

POST https://eventmakers-api.vercel.app/api/join-events

{
    "name": "",
    "email": "",
    "phone": "",
    "eventId": ""
}